let shopItemsData = [
    {
    id: "1",
    name: "T-Shirt",
    price: 8,
    desc: "this is the white T shirt made in India 100% pure cotton",
    img: "images/1.jpg",
},
{
    id: "2",
    name: "T-Shirt",
    price: 7,
    desc: "this is an printed T shirt made in India 100% pure cotton",
    img: "images/2.jpg",
},
{
    id: "3",
    name: "Blue Shirt",
    price: 7,
    desc: "Very Fine Fabric",
    img: "images/3.jpg",
},
{
    id: "4",
    name: "Shirt",
    price: 7,
    desc: "A party ware shirt",
    img: "images/4.jpg",
},
{
    id: "5",
    name: "Black Watch",
    price: 15,
    desc: "A stylish office ware Watch",
    img: "images/5.jpg",
},
{
id: "6",
    name: "Blue Watch",
    price: 20,
    desc: "good watch",
    img: "images/6.jpg",
},
{
id: "7",
    name: "Watch",
    price: 19.99,
    desc: "fabulous watch",
    img: "images/7.jpg",
},
{
 id: "8",
    name: "Trainer Shoes",
    price: 40,
    desc: "tranier shoes",
    img: "images/8.jpg",
},
{
id: "9",
    name: "Shoes",
    price: 39.99,
    desc: "Trainer Shoe",
    img: "images/9.jpg",
},
{
id: "10",
    name: "Nike Shoe",
    price: 69.99,
    desc: "Nike Shoe",
    img: "images/10.jpg",
},
{
id: "11",
    name: "Watch",
    price: 25,
    desc: "Watch",
    img: "images/11.jpg",
},
{
id: "12",
    name: "Watch",
    price: 30,
    desc: "Watch",
    img: "images/12.jpg",
}
]
